from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    rooms = list()
    rooms.append(dict(room="01.05.001", description="Corridor"))
    rooms.append(dict(room="01.05.012", description="Internship room"))
    rooms.append(dict(room="01.05.013", description="Internship room"))
    rooms.append(dict(room="01.05.014A", description="Copiers"))
    rooms.append(dict(room="01.05.014B", description="Lounge"))
    rooms.append(dict(room="01.05.015", description="Elevator"))
    rooms.append(dict(room="01.05.016", description="Corridor"))
    rooms.append(dict(room="01.05.020", description="Storage"))
    rooms.append(dict(room="01.05.030", description="Corridor"))
    rooms.append(dict(room="01.05.031", description="Tea kitchen"))
    rooms.append(dict(room="01.05.033", description="Working room for students"))
    rooms.append(dict(room="01.05.034A", description="Server room"))
    rooms.append(dict(room="01.05.034B", description="Copy room"))
    rooms.append(dict(room="01.05.036", description="Office"))
    rooms.append(dict(room="01.05.037", description="Office"))
    rooms.append(dict(room="01.05.038", description="Office"))
    rooms.append(dict(room="01.05.039", description="Office"))
    rooms.append(dict(room="01.05.040", description="Office"))
    rooms.append(dict(room="01.05.041", description="Office"))
    rooms.append(dict(room="01.05.042", description="Office"))
    rooms.append(dict(room="01.05.043", description="Office"))
    rooms.append(dict(room="01.05.044", description="Office"))
    rooms.append(dict(room="01.05.050", description="Corridor"))
    rooms.append(dict(room="01.05.051", description="Meeting room"))
    rooms.append(dict(room="01.05.052", description="Office"))
    rooms.append(dict(room="01.05.053", description="Office"))
    rooms.append(dict(room="01.05.054", description="Office"))
    rooms.append(dict(room="01.05.055", description="Office"))
    rooms.append(dict(room="01.05.057", description="Office"))
    rooms.append(dict(room="01.05.058", description="Seminar room"))
    rooms.append(dict(room="01.05.059", description="Office"))
    rooms.append(dict(room="01.05.060", description="Office"))
    rooms.append(dict(room="01.05.061", description="Office"))
    rooms.append(dict(room="01.05.101", description="Stairway"))
    rooms.append(dict(room="01.05.102", description="Stairway"))
    
    services = list()
    services.append(dict(name="Device coupling"))    
    services.append(dict(name="Navigation"))
    services.append(dict(name="Messaging"))
    
    return render_template('index.html', services=services, rooms=rooms)

if __name__ == '__main__':
    app.run()
